INSERT INTO Barco (modelo, tipo, capacidade, descricao, preco_aluguel) VALUES
('Ocean Master 500', 'Lancha', 8, 'Lancha para passeios costeiros', 500.00),
('Sunset Cruiser', 'Veleiro', 6, 'Veleiro para cruzeiros relaxantes', 800.00),
('Speedy Runner', 'Jet Ski', 2, 'Jet Ski para aventuras aquáticas', 300.00),
('Sea Breeze', 'Iate', 10, 'Iate luxuoso para viagens marítimas', 1200.00),
('Coral Explorer', 'Catamarã', 12, 'Catamarã para mergulho e exploração', 900.00),
('Wave Rider', 'Lancha', 6, 'Lancha rápida para esportes aquáticos', 600.00),
('Breeze Catcher', 'Veleiro', 4, 'Veleiro clássico para viagens tranquilas', 700.00),
('Aqua Rocket', 'Jet Ski', 2, 'Jet Ski potente para aventuras emocionantes', 350.00),
('Ocean Whisperer', 'Iate', 8, 'Iate elegante para viagens exclusivas', 1500.00),
('Island Hopper', 'Catamarã', 14, 'Catamarã espaçoso para passeios em grupo', 1000.00),
('Sailor\'s Dream', 'Veleiro', 5, 'Veleiro confortável para cruzeiros longos', 750.00),
('Tidal Thrill', 'Lancha', 4, 'Lancha ágil para passeios em alta velocidade', 550.00),
('Splash Master', 'Jet Ski', 3, 'Jet Ski resistente para uso recreativo', 400.00),
('Royal Mariner', 'Iate', 12, 'Iate luxuoso com todos os confortos', 1800.00),
('Island Seeker', 'Catamarã', 10, 'Catamarã estável para exploração costeira', 850.00),
('Seabreeze Serenity', 'Veleiro', 7, 'Veleiro espaçoso para viagens relaxantes', 900.00),
('Sunset Skimmer', 'Lancha', 6, 'Lancha moderna para passeios ao pôr do sol', 700.00),
('Aqua Glide', 'Jet Ski', 2, 'Jet Ski ágil para diversão na água', 300.00),
('Luxury Liner', 'Iate', 15, 'Iate de luxo para viagens de alto padrão', 2000.00),
('Coastal Explorer', 'Catamarã', 16, 'Catamarã robusto para exploração marinha', 1100.00);
